In [1]:
import tensorflow as tf
import numpy as np
print(tf.test.is_built_with_cuda())
tf.config.list_physical_devices('GPU')

True


[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [3]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()

In [4]:
x_train, x_test = x_train / 255.0, x_test / 255.0

In [6]:
x_train.shape

(60000, 28, 28)

In [30]:
x = [[2.]]
m = tf.matmul(x, x)
print("hello, {}".format(m))

hello, [[4.]]


In [54]:
model = tf.keras.Sequential()
model.add(tf.keras.layers.Flatten(input_shape=(28, 28)))
model.add(tf.keras.layers.Dense(128, activation='relu'))
model.add(tf.keras.layers.Dropout(0.2))
model.add(tf.keras.layers.Dense(10))
print(model.input_shape)
print(model.output_shape)

(None, 28, 28)
(None, 10)


In [56]:
predictions = model(x_train[:1]).numpy()
predictions

array([[ 0.11070166,  0.21407072, -0.0931119 ,  0.02396189,  0.25976333,
         0.00062557, -0.16057843, -0.2549437 , -0.14891797,  0.2648745 ]],
      dtype=float32)

In [63]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)
loss_fn(y_train[:1], predictions).numpy()

2.339244

In [64]:
y_train

array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

In [60]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 3s 1ms/step - loss: 0.2902 - accuracy: 0.9172
Epoch 2/5
1875/1875 [==============================] - 3s 1ms/step - loss: 0.1443 - accuracy: 0.9570
Epoch 3/5
1875/1875 [==============================] - 3s 1ms/step - loss: 0.1069 - accuracy: 0.9669
Epoch 4/5
1875/1875 [==============================] - 3s 1ms/step - loss: 0.0892 - accuracy: 0.9732
Epoch 5/5
1875/1875 [==============================] - 3s 1ms/step - loss: 0.0738 - accuracy: 0.9766


In [61]:
model.evaluate(x_test,  y_test, verbose=2)

313/313 - 0s - loss: 0.0736 - accuracy: 0.9768


[0.07355374097824097, 0.9768000245094299]

In [62]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])
probability_model(x_test[:1])

<tf.Tensor: shape=(1, 10), dtype=float32, numpy=
array([[6.6439156e-07, 5.9646815e-08, 5.7217603e-06, 2.8883427e-04,
        1.8620451e-11, 2.6971527e-06, 2.6773525e-12, 9.9954212e-01,
        4.8971397e-06, 1.5505942e-04]], dtype=float32)>

In [2]:
loaded = tf.saved_model.load("saved_models/my_model")

In [4]:
dir(loaded)

['__call__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_add_variable_with_custom_getter',
 '_checkpoint_dependencies',
 '_default_save_signature',
 '_deferred_dependencies',
 '_gather_saveables_for_checkpoint',
 '_handle_deferred_dependencies',
 '_list_extra_dependencies_for_serialization',
 '_list_functions_for_serialization',
 '_lookup_dependency',
 '_map_resources',
 '_maybe_initialize_trackable',
 '_name_based_attribute_restore',
 '_name_based_restores',
 '_no_dependency',
 '_object_identifier',
 '_preload_simple_restoration',
 '_restore_from_checkpoint_position',
 '_self_name_based_restores',
 '_self_saveable_object_factories',
 '_self_setattr_tracking',
 '

In [ ]:
# Image.fromarray(test_result)
# im.save('test.jpg')
# plt.savefig(test_result)
cv2.imread(test_result)